logo:
  subtitle: '十年饮冰 | 难凉热血'
article:
  # auto_cover: true
  auto_excerpt: 200 # 自动生成200字摘要

menubar:
  columns: 4 # 一行多少个
  items: # 可按照自己需求增加，符合以下格式即可
     - id: post # 页面中高亮的 menu_id
       theme: '#1BCDFC' # 高亮时的颜色，仅 svg 中 fill="currentColor" 时有效
       icon: solar:documents-bold-duotone # 支持 svg/img 标签，可以定义在 icons.yml 文件中，也支持外部图片的 URL
       title: 博客 # 标题
       url: / # 跳转链接，支持相对路径和绝对路径
     - id: wiki
       theme: '#3DC550'
       icon: solar:notebook-bookmark-bold-duotone
       title: 文档
       url: /wiki/
     - id: explore
       theme: '#FA6400'
       icon: solar:planet-bold-duotone
       title: 探索
       url: /explore/
     - id: social
       theme: '#F44336'
       icon: solar:chat-square-like-bold-duotone
       title: 社交
       url: /friends/
# 文章搜索
search:
  service: local_search # local_search, todo...
  local_search: # 在 front-matter 中设置 indexing:false 来避免被搜索索引
    field: all # post, page, all
    path: /search.json # 搜索文件存放位置
    content: true # 是否搜索内容
    # codeblock: true # 是否搜索代码块（需要content: true)
# 默认打开
comments:
  service: beaudar
  beaudar:
    repo: invalidsyntaxxx/invalidsyntaxxx.github.io

footer:
  content: 
    <script>
    var _hmt = _hmt || [];
    (function() {
    var hm = document.createElement("script");
    hm.src = "https://hm.baidu.com/hm.js?6370921ce400c5d93138974cc79784ac";
    var s = document.getElementsByTagName("script")[0]; 
    s.parentNode.insertBefore(hm, s);})();
    </script>

    <span>桂ICP备2024024328号</span>
